unexpected error 'list' object has no attribute 'get' for group 97b99d50-bc67-4e69-84d3-1c78e0c7db21
unexpected error Request failed with status 415,Response: {"error":{"code":"InvalidRequest","message":"Invalid dataset. This API can only be called on a Model-based dataset"}} for group 97b99d50-bc67-4e69-84d3-1c78e0c7db21


get_object_type_items(access_token, "datasets", "id", "refreshes")
